"use client"
import "./globals.css"
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import { ThirdwebProvider } from "@thirdweb-dev/react"
import { Navbar } from "@/components/Navbar"
import { THIRDWEB_CLIENT_ID } from "@/constants"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<ThirdwebProvider
					activeChain='mumbai'
					clientId={THIRDWEB_CLIENT_ID}
				>
					<Navbar />
					{children}
				</ThirdwebProvider>
			</body>
		</html>
	)
}
